eureka:
  client:
    region: default
    registryFetchIntervalSeconds: 10
    serviceUrl:
      defaultZone: http://DEV_DISCOVERY_USERNAME:DEV_DISCOVERY_PASSWORD@localhost:8761/eureka

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9999/realms/scrumly
          jwk-set-uri: http://localhost:9999/realms/scrumly/protocol/openid-connect/certs
